name = "Acme-ICan-tBelieveItCanSort"
badges = ["github-actions/linux.yml", "github-actions/windows.yml", "github-actions/macos.yml", "metacpan"]
module_maker = "ModuleBuildTiny"
static_install = "auto"
license = "artistic_2"
authority = "cpan:SANKO"
